sonar.projectKey=gatodemontecristo_survey-rimac-short
sonar.organization=gatodemontecristo


sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.test.tsx,**/*.test.ts,dist/**,**/dist/**,coverage/**,**/coverage/**,stories/**,**/stories/**,**/constants/**,**/router/**,**/store/**,**/components/organisms/**/*,index.css
sonar.tests=src
sonar.test.inclusions=**/*.test.tsx,**/*.test.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8