import { ItemOption } from '../types';

export const anotherOptions: ItemOption[] = [
  { value: 'acne', label: 'Acné' },
  { value: 'rinitis_alergica', label: 'Rinitis alérgica' },
  { value: 'anemia', label: 'Anemia' },
  { value: 'asma', label: 'Asma' },
  { value: 'cancer_colon', label: 'Cáncer de colon' },
  { value: 'cancer_mama', label: 'Cáncer de mama' },
  { value: 'cancer_ovario', label: 'Cáncer de ovario' },
  { value: 'cancer_piel', label: 'Cáncer de piel' },
  { value: 'cancer_prostata', label: 'Cáncer de próstata' },
  { value: 'cancer_pulmon', label: 'Cáncer de pulmón' },
  { value: 'cancer_cerebral', label: 'Cáncer cerebral' },
  { value: 'enfermedad_corazon', label: 'Enfermedad crónica del corazón' },
  { value: 'catarata', label: 'Catarata' },
  {
    value: 'colelitiasis',
    label: 'Colelitiasis: presencia de cálculos biliares',
  },
  { value: 'diabetes', label: 'Diabetes mellitus' },
  {
    value: 'lipidemias',
    label: 'Trastornos del metabolismo de las lipoproteínas y otras lipidemias',
  },
  { value: 'enfermedad_renal', label: 'Enfermedad renal crónica' },
  { value: 'enfermedades_higado', label: 'Otras enfermedades del hígado' },
  { value: 'ulcera_gastrica', label: 'Úlcera gástrica' },
  { value: 'artritis_reumatoide', label: 'Artritis reumatoide' },
  { value: 'condiciones_pulmonares', label: 'Condiciones pulmonares crónicas' },
  { value: 'gota', label: 'Gota' },
  { value: 'hipertension', label: 'Hipertensión esencial' },
  { value: 'hipertiroidismo', label: 'Hipertiroidismo' },
  { value: 'hipotiroidismo', label: 'Hipotiroidismo' },
  { value: 'vih', label: 'VIH - virus de inmunodeficiencia' },
  { value: 'insuficiencia_cardiaca', label: 'Insuficiencia cardiaca' },
  { value: 'leiomioma_utero', label: 'Leiomioma del útero' },
  { value: 'cancer_cuello_uterino', label: 'Cáncer de cuello uterino' },
  { value: 'cancer_estomago', label: 'Cáncer de estómago' },
  { value: 'cancer_tiroides', label: 'Cáncer de la glándula tiroides' },
  { value: 'cancer_pancreas', label: 'Cáncer de páncreas' },
  { value: 'cancer_recto', label: 'Cáncer de recto' },
  { value: 'cancer_rinon', label: 'Cáncer de riñón' },
  { value: 'derrame_cerebral', label: 'Derrame cerebral' },
  {
    value: 'enfermedades_pulmonares',
    label: 'Enfermedades pulmonares que afectan el tejido intersticial',
  },
  { value: 'glaucoma', label: 'Glaucoma' },
  {
    value: 'infecciones_respiratorias',
    label: 'Infecciones respiratorias superiores',
  },
  { value: 'lesion_hombro', label: 'Lesiones en el hombro' },
  { value: 'lesion_rodilla', label: 'Lesiones en la rodilla' },
  { value: 'lesion_tobillo', label: 'Lesiones en tobillo y/o pie' },
  { value: 'reflujo_gastroesofagico', label: 'Reflujo ácido gastroesofágico' },
  { value: 'trastorno_vision', label: 'Trastorno de visión' },
  { value: 'trastornos_retina', label: 'Trastornos en la retina' },
  {
    value: 'trastornos_nasales',
    label: 'Trastornos nasales y de los senos paranasales',
  },
  { value: 'traumatismo_hombro', label: 'Traumatismo en hombro y el brazo' },
  { value: 'traumatismo_mano', label: 'Traumatismo en la muñeca y/o mano' },
  { value: 'colecistitis', label: 'Colecistitis' },
  { value: 'apendicitis', label: 'Apendicitis' },
  { value: 'calculos_rinon', label: 'Cálculos en los riñones o uréter' },
  { value: 'crisis_hipertensiva', label: 'Crisis hipertensiva' },
  {
    value: 'enfermedades_cerebrovasculares',
    label: 'Enfermedad cerebrovascular',
  },
  { value: 'esclerosis_multiple', label: 'Esclerosis múltiple' },
  { value: 'espondilitis', label: 'Espondilitis Anquilosante' },
  { value: 'fibrilacion_auricular', label: 'Fibrilación y aleteo auricular' },
  { value: 'fiebre_dengue', label: 'Fiebre del dengue' },
  { value: 'gastritis_duodenitis', label: 'Gastritis o Duodenitis' },
  { value: 'hiperplasia_prostata', label: 'Hiperplasia de próstata' },
  { value: 'insuficiencia_respiratoria', label: 'Insuficiencia respiratoria' },
  { value: 'psoriasis', label: 'Psoriasis' },
  { value: 'trastornos_columna', label: 'Trastornos de la columna vertebral' },
  {
    value: 'trastornos_glandulas_lagrimales',
    label: 'Trastornos de las glándulas lagrimales',
  },
  {
    value: 'trastornos_discos_columna',
    label: 'Trastornos de los discos de la columna',
  },
  { value: 'trastornos_rotula', label: 'Trastornos de rótula' },
  { value: 'trastornos_urinarios', label: 'Trastornos del sistema urinario' },
  {
    value: 'trastornos_articulaciones',
    label: 'Trastornos en las articulaciones',
  },
  {
    value: 'sindrome_intestino_irritable',
    label: 'Síndrome del intestino irritable',
  },
  { value: 'embolia_trombosis', label: 'Embolia o trombosis' },
  {
    value: 'cancer_medula_osea',
    label: 'Cáncer de las células plasmáticas en la médula ósea',
  },
  { value: 'leucemia_linfoide', label: 'Leucemia Linfoide' },
  { value: 'leucemia_mieloide', label: 'Leucemia Mieloide' },
  { value: 'vitiligo', label: 'Vitiligo' },
  { value: 'ninguna', label: 'Ninguna' },
  { value: 'otros', label: 'Otros' },
];
